var projectSection = '<div class="project row" id="project-%num%"> <div class="col-xs-9"> <p class="project-header">Project %num%</p> </div> <div class="col-xs-3"> <button class="btn btn-danger btn-sm pull-right section-close-btn project-close-btn" onclick="removeSection(this);"><span class="glyphicon glyphicon-trash"></span> </button> </div> <div class="col-xs-9"> <textarea class="form-control project-text-area-1" id="project-%num%-text-area-1" type="text" placeholder="Special Project"></textarea> </div> <div class="col-xs-3" role="group" aria-label="Rating:"><span class="rating-label">Choose Rating:<br></span> <div class="btn-group"> <button type="button" class="btn btn-default rating-btn left-btn" value="I">I</button> <button type="button" class="btn btn-default rating-btn" value="SP-">SP-</button> <button type="button" class="btn btn-default rating-btn" value="SP">SP</button> <button type="button" class="btn btn-default rating-btn" value="SP+">SP+</button> <button type="button" class="btn btn-default rating-btn" value="O">O</button> </div> </div> <div class="col-xs-9"> <textarea class="form-control project-text-area-2" id="project-%num%-text-area-2" type="text" placeholder="Standard"></textarea> </div> <div class="col-xs-9"> <textarea class="form-control project-text-area-3" id="project-%num%-text-area-3" type="text" placeholder="Comments (are not required for a rating of &quot;SP&quot;)"></textarea> </div> <div class="input-group input-append col-xs-3 date dateRangePicker" id="dateRangePicker-%num%"> <input type="text" class="form-control project-due-date date date-picker" name="date" placeholder="Due Date..." /><span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span> </div></div>';

var numOfProjects = 0;
function addProject(){
    var formattedSection = projectSection.replace(/%num%/g, numOfProjects+1);
    numOfProjects++;
    $('#projects-container').append(formattedSection);
    addButtonToolTips();
    updateDynamicallyAddedTextAreas();
}